// Unit coverage for the notification message renderers (#92 phase 2).
//
// Fixtures are generated by the REAL producer functions (buildWakeFailureDiagnostic,
// formatExecutionEvent, formatResearchCompletion, the scheduler formatters, and
// formatWakePayload) so the collapsed/expanded contract is pinned against the
// actual shapes — not hand-crafted approximations. A minimal fake pi-tui
// (wrapTextWithAnsi only, no MouseRegion) drives width; click handling is covered
// by the real-host file. The expanded view must always be the complete existing
// notification text; unknown/historical/malformed content falls back to the full
// retained content rather than a misleading summary.
import assert from "node:assert/strict";
import test from "node:test";
import {
  setPiTuiHost,
  renderSubtaskEventCollapsed,
  renderBgShellCollapsed,
  renderSubtaskWatchCollapsed,
  renderScheduledTaskEventCollapsed,
  renderScheduledOrchestratorTurnCollapsed,
  renderFullMessageContent,
  registerNotificationMessageRenderers,
  NOTIFICATION_MESSAGE_TYPES,
} from "../src/message-expansion";
import {
  buildWakeFailureDiagnostic,
  formatExecutionEvent,
  formatResearchCompletion,
} from "../src/execution/subtask-notifications";
import {
  formatScheduledSkipEvent,
  formatScheduledOneShotPendingSkip,
  formatScheduledOverdueDrop,
  formatScheduledDispatchFailure,
  formatScheduledOrchestratorDeliveryFailure,
  formatScheduledOrchestratorDeliveryUncertain,
} from "../src/scheduling/events";
import { formatWakePayload } from "../src/background-shell/jobs";

// A minimal fake pi-tui: naive hard-wrap (content in these tests is short), no
// MouseRegion so the core adapter degrades to keyboard-only rendering.
setPiTuiHost({
  wrapTextWithAnsi: (text: string, width: number): string[] => {
    if (width <= 0) return text.split(/\n/);
    return text.split(/\n/).flatMap((line) => {
      if (line.length <= width) return [line];
      const chunks: string[] = [];
      for (let i = 0; i < line.length; i += width) chunks.push(line.slice(i, i + width));
      return chunks;
    });
  },
});

const THEME = { bold: (t: string) => t, fg: (_c: string, t: string) => t };
function lines(component: unknown, width = 100): string[] {
  return (component as { render(w: number): string[] }).render(width);
}

// ── Real producer fixtures (minimal shapes, cast to the producer's types) ────

function makeGroup(kind: "execute" | "research" | "inplace", tasks: unknown[]): Record<string, unknown> {
  return {
    version: 3, revision: 1, integritySha256: "x", executionId: "exec-1", kind, root: "/tmp/root", cwd: "/tmp/cwd",
    createdAt: "", updatedAt: "", tasks, totalTaskCount: tasks.length, settledArchivedCount: 0,
  };
}
function makeTask(taskId: string, title: string, state: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return { taskId, definition: { title, instructions: "i", acceptanceCriteria: [] }, state, createdAt: "", updatedAt: "", generation: 1, activity: [], ...extra };
}
function makeEntry(name: string, cron = "0 2 * * *"): Record<string, unknown> {
  return { name, cron, enabled: true, kind: "execute", instructions: "" };
}
const DUE = new Date("2026-01-01T02:00:00Z");

// ── pi-review-subtask-event ──────────────────────────────────────────────────

test("subtask-event collapsed: real completion fixture shows title + state + count", () => {
  const group = makeGroup("execute", [makeTask("t-1", "Implement feature X", "landed"), makeTask("t-2", "Another task", "running")]);
  const content = formatExecutionEvent(group as never, makeTask("t-1", "Implement feature X", "landed") as never, "state", "Worker reported completion.");
  const message = { role: "custom", customType: "pi-review-subtask-event", content, display: true, details: { state: "landed", executionId: "exec-1" } };
  const out = lines(renderSubtaskEventCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("[subtask]"), "family label present");
  assert.ok(out.includes("Implement feature X"), "recorded title present");
  assert.ok(out.includes("LANDED"), "actual outcome state shown");
  assert.ok(out.includes("1/2"), "aggregate count from the execution line");
});

test("subtask-event collapsed: real conflict diagnostic shows error, notice, and EVERY recovery action", () => {
  const task = makeTask("t-9", "Land the migration", "conflicted", { bundle: { waveRoot: "/tmp/w" }, error: "merge conflict in src/a.ts", summary: "landing blocked" });
  const group = makeGroup("execute", [task]);
  const diagnostic = buildWakeFailureDiagnostic({
    group: group as never, task: task as never, content: "The task failed during landing.",
    conflictGate: { paths: ["src/a.ts", "src/b.ts"], manifestPath: "/tmp/m.json", reason: "two owners touched a.ts" },
  });
  const message = { role: "custom", customType: "pi-review-subtask-event", content: `Task: t-9 · Land the migration · conflicted`, display: true, details: { state: "conflicted", diagnostic } };
  // Wide width so the bounded (up to 600-char) recovery actions are not wrapped.
  const out = lines(renderSubtaskEventCollapsed(message, {}, THEME), 1000).join("\n");
  assert.ok(out.includes("CONFLICTED"), "conflict state shown");
  assert.ok(out.includes("merge conflict in src/a.ts"), "error detail shown");
  assert.ok(out.includes("The task failed during landing."), "immediate notice shown alongside the error (not suppressed)");
  assert.ok(out.includes("src/a.ts, src/b.ts"), "conflict paths shown");
  // Every bounded recovery instruction is visible — not just the first. The
  // producer orders SubtasksInspect first, then conflict/continuation/interrupt.
  for (const action of diagnostic.recovery.suggestedActions) {
    assert.ok(out.includes(action), `recovery action visible: ${action.slice(0, 40)}…`);
  }
  assert.ok(out.includes("SubtasksInspect"), "inspect-first ordering preserved");
  assert.ok(out.includes("SubtasksMarkClean"), "conflict resolution instruction not hidden");
  assert.ok(out.includes("SubtasksInterrupt"), "live-writer interruption instruction not hidden");
});

test("subtask-event collapsed: real recoverable-stop diagnostic surfaces continuation + interrupt", () => {
  const task = makeTask("t-7", "Do the work", "paused_recoverable", { bundle: { waveRoot: "/tmp/w" }, error: "paused by operator" });
  const group = makeGroup("execute", [task]);
  const diagnostic = buildWakeFailureDiagnostic({ group: group as never, task: task as never, content: "Task paused." });
  const message = { role: "custom", customType: "pi-review-subtask-event", content: `Task: t-7 · Do the work · paused_recoverable`, display: true, details: { state: "paused_recoverable", diagnostic } };
  const out = lines(renderSubtaskEventCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("PAUSED (RECOVERABLE)"), "recovery state shown");
  assert.ok(out.includes("SubtasksContinue"), "continuation instruction visible");
  assert.ok(out.includes("SubtasksInterrupt"), "interrupt instruction visible");
});

test("subtask-event collapsed: research completion count comes from the aggregate line, not an inlined report ratio", () => {
  // The report mentions the execution id with an unrelated ratio (2/9) BEFORE
  // the producer's aggregate (1/2); the collapsed count must be the anchored
  // producer aggregate, not the report's ratio.
  const group = makeGroup("research", [makeTask("t-3", "Research topic", "reported"), makeTask("t-4", "Other research", "running")]);
  const report = formatResearchCompletion("t-3", "For exec-1 we tested 2/9 cases and found a bug.", "/tmp/report.md");
  const content = formatExecutionEvent(group as never, makeTask("t-3", "Research topic", "reported") as never, "completion", report);
  const message = { role: "custom", customType: "pi-review-subtask-event", content, display: true, details: { state: "reported", executionId: "exec-1" } };
  const out = lines(renderSubtaskEventCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("1/2"), "count from the anchored producer aggregate line");
  assert.ok(!out.includes("· 2/9"), "the inlined report ratio (even with the exec id) is not the task count");
  assert.ok(out.includes("Full report: /tmp/report.md"), "full report reference preserved (unshortened)");
});

test("subtask-event collapsed: historical Task line with state but no details still shows the recorded state", () => {
  const message = { role: "custom", customType: "pi-review-subtask-event", content: "Task: t-5 · Do the work · landed\nExecution exec-1 COMPLETE: 1/1 tasks landed.", display: true };
  const out = lines(renderSubtaskEventCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("Do the work"), "title from the Task line");
  assert.ok(out.includes("LANDED"), "state recovered from the Task line (no details needed)");
});

test("subtask-event collapsed: failure without a usable diagnostic falls back to full content", () => {
  // A failed state with an empty diagnostic {} cannot be compacted to its
  // header — that would hide the retained failure/recovery instructions. The
  // full retained content is shown instead.
  const emptyDiag = { role: "custom", customType: "pi-review-subtask-event", content: "Task: t-1 · X · failed\nResolve src/a.ts before continuing.", display: true, details: { state: "failed", diagnostic: {} } };
  assert.equal(lines(renderSubtaskEventCollapsed(emptyDiag, {}, THEME)).join("\n"), "Task: t-1 · X · failed\nResolve src/a.ts before continuing.");
  // A historical failed message with a valid Task line but NO diagnostic at all
  // also falls back (a recorded state alone is not safe to compact).
  const noDiag = { role: "custom", customType: "pi-review-subtask-event", content: "Task: t-1 · X · conflicted\nResolve src/a.ts before continuing.", display: true, details: { state: "conflicted" } };
  assert.equal(lines(renderSubtaskEventCollapsed(noDiag, {}, THEME)).join("\n"), "Task: t-1 · X · conflicted\nResolve src/a.ts before continuing.");
  // A malformed Task line (no title/state) with no valid diagnostic falls back.
  const malformed = { role: "custom", customType: "pi-review-subtask-event", content: "Task: t-1 only\nSome unstructured text.", display: true };
  assert.equal(lines(renderSubtaskEventCollapsed(malformed, {}, THEME)).join("\n"), "Task: t-1 only\nSome unstructured text.");
});

// ── pi-review-bg-shell ───────────────────────────────────────────────────────

test("bg-shell collapsed: real failed-exit payload keeps the diagnostic excerpt visible", () => {
  const content = formatWakePayload({
    id: "job-42", label: "build", command: "npm run build", event: { kind: "exit", lane: "now", reason: "exited 1" },
    elapsedMs: 12000, exitCode: 1, lines: ["compiling…", "error TS2304: cannot find name 'foo'"], totalLines: 2,
  });
  const message = { role: "custom", customType: "pi-review-bg-shell", content, display: true, details: { id: "job-42", kind: "exit" } };
  const out = lines(renderBgShellCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("[bg-shell] build (job-42)"), "identity shown");
  assert.ok(out.includes("· exit 1"), "nonzero exit shown");
  assert.ok(out.includes("error TS2304: cannot find name 'foo'"), "diagnostic excerpt is NOT hidden for a failed job");
});

test("bg-shell collapsed: real matched-error wake keeps the matched line visible", () => {
  const content = formatWakePayload({
    id: "job-7", label: "server", command: "node server.js", event: { kind: "match", lane: "now", reason: 'matched "Traceback"' },
    elapsedMs: 5000, exitCode: null, lines: ["listening on :3000", "Traceback (most recent call last):"], totalLines: 2,
  });
  const message = { role: "custom", customType: "pi-review-bg-shell", content, display: true, details: { id: "job-7", kind: "match" } };
  const out = lines(renderBgShellCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes('matched "Traceback"'), "match reason shown");
  assert.ok(out.includes("Traceback (most recent call last):"), "matched line visible for a match wake");
});

test("bg-shell collapsed: success exit is summarized without the excerpt", () => {
  const content = formatWakePayload({
    id: "job-1", label: "build", command: "npm run build", event: { kind: "exit", lane: "soon", reason: "exited 0" },
    elapsedMs: 3000, exitCode: 0, lines: ["compiled successfully"], totalLines: 1,
  });
  const message = { role: "custom", customType: "pi-review-bg-shell", content, display: true, details: { id: "job-1", kind: "exit" } };
  const out = lines(renderBgShellCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("· exit 0"), "success exit shown");
  assert.equal(out.includes("compiled successfully"), false, "non-actionable success excerpt omitted from the summary");
});

test("bg-shell collapsed: unrecognized payload falls back to full text (id alone is not enough)", () => {
  const message = { role: "custom", customType: "pi-review-bg-shell", content: "not a wake payload at all", display: true, details: { id: "j-1" } };
  assert.equal(lines(renderBgShellCollapsed(message, {}, THEME)).join("\n"), "not a wake payload at all");
});

test("bg-shell collapsed: a 12-line failed-exit excerpt keeps its early diagnostic visible", () => {
  // The producer supplies up to the full bounded excerpt; the collapsed view
  // must not re-truncate it (slice(-8) would hide an error in the first lines).
  const filler = Array.from({ length: 11 }, (_, i) => `context line ${i + 1}`);
  const content = formatWakePayload({
    id: "job-9", label: "build", command: "npm run build", event: { kind: "exit", lane: "now", reason: "exited 2" },
    elapsedMs: 8000, exitCode: 2, lines: ["error TS2304: cannot find name 'foo'", ...filler], totalLines: 12,
  });
  const message = { role: "custom", customType: "pi-review-bg-shell", content, display: true, details: { id: "job-9", kind: "exit" } };
  const out = lines(renderBgShellCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("error TS2304: cannot find name 'foo'"), "the early diagnostic is NOT hidden by re-truncation");
  assert.ok(out.includes("context line 11"), "the complete bounded excerpt is retained");
});

test("bg-shell collapsed: a literal fence inside command output does not end the excerpt early", () => {
  const content = formatWakePayload({
    id: "job-10", label: "gen", command: "node gen.js", event: { kind: "exit", lane: "now", reason: "exited 1" },
    elapsedMs: 2000, exitCode: 1, lines: ["```", "error: unexpected token"], totalLines: 2,
  });
  const message = { role: "custom", customType: "pi-review-bg-shell", content, display: true, details: { id: "job-10", kind: "exit" } };
  const out = lines(renderBgShellCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("error: unexpected token"), "the diagnostic after an embedded fence is still extracted");
});

// ── pi-review-subtask-watch ──────────────────────────────────────────────────

test("subtask-watch collapsed: active-work checkpoint from structured details", () => {
  const message = {
    role: "custom", customType: "pi-review-subtask-watch",
    content: "[pi-review-subtask-watch]\nThe requested one-shot checkpoint for execution exec-1 is due while work remains active.",
    display: true,
    details: { executions: [{ executionId: "exec-1", kind: "execute", revision: 3, tasks: [{ state: "running" }, { state: "reviewing" }, { state: "landed" }] }] },
  };
  const out = lines(renderSubtaskWatchCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("[subtask-watch]"), "family label present");
  assert.ok(out.includes("exec-1: 2 active task(s)"), "active count (landed excluded)");
});

test("subtask-watch collapsed: malformed details fall back instead of fabricating or throwing", () => {
  // executions: [{}] has no tasks array — must not fabricate a zero count.
  const emptyExec = { role: "custom", customType: "pi-review-subtask-watch", content: "[pi-review-subtask-watch]\ncheckpoint", display: true, details: { executions: [{}] } };
  assert.equal(lines(renderSubtaskWatchCollapsed(emptyExec, {}, THEME)).join("\n"), "[pi-review-subtask-watch]\ncheckpoint");
  // tasks: [null] must not throw during render.
  const nullTask = { role: "custom", customType: "pi-review-subtask-watch", content: "[pi-review-subtask-watch]\ncheckpoint", display: true, details: { executions: [{ executionId: "e", tasks: [null] }] } };
  assert.equal(lines(renderSubtaskWatchCollapsed(nullTask, {}, THEME)).join("\n"), "[pi-review-subtask-watch]\ncheckpoint");
  // An unknown task state is not a reliable snapshot — fall back rather than
  // silently count it as inactive.
  const unknownState = { role: "custom", customType: "pi-review-subtask-watch", content: "[pi-review-subtask-watch]\ncheckpoint", display: true, details: { executions: [{ executionId: "e", tasks: [{ state: "bogus_state" }] }] } };
  assert.equal(lines(renderSubtaskWatchCollapsed(unknownState, {}, THEME)).join("\n"), "[pi-review-subtask-watch]\ncheckpoint");
});

// ── pi-review-scheduled-task-event ───────────────────────────────────────────

test("scheduled-task-event collapsed: uncertain delivery is not mislabeled by an entry name containing 'dispatch failed'", () => {
  const content = formatScheduledOrchestratorDeliveryUncertain("e-6", makeEntry("dispatch failed monitor") as never, DUE);
  const message = { role: "custom", customType: "pi-review-scheduled-task-event", content, display: true };
  const out = lines(renderScheduledTaskEventCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("UNKNOWN (MAY STILL ARRIVE)"), "uncertain outcome recognized from its own clause, not the entry name");
  assert.ok(!out.includes("DISPATCH FAILED"), "entry name 'dispatch failed' does not flip the status");
  assert.ok(out.includes("Inspect the conversation before retrying"), "duplicate-retry warning stays in the collapsed view");
});

test("scheduled-task-event collapsed: real dispatch-failure, delivery-failure, and overlap-skip keep error + action lines", () => {
  const dispatch = formatScheduledDispatchFailure("e-4", makeEntry("Broken") as never, DUE, "the entry has no workspace");
  const dOut = lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content: dispatch, display: true }, {}, THEME)).join("\n");
  assert.ok(dOut.includes("DISPATCH FAILED"), "dispatch failure status");
  assert.ok(dOut.includes("the entry has no workspace"), "bounded error shown");
  assert.ok(dOut.includes("Fix the entry or its worker/review choices"), "repair instruction preserved");

  const delivery = formatScheduledOrchestratorDeliveryFailure("e-5", makeEntry("Down") as never, DUE, "channel closed");
  const dlvOut = lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content: delivery, display: true }, {}, THEME)).join("\n");
  assert.ok(dlvOut.includes("NOT DELIVERED"), "delivery failure status");
  assert.ok(dlvOut.includes("channel closed"), "bounded error shown");
  assert.ok(dlvOut.includes("Repair the delivery channel"), "repair instruction preserved");

  const skip = formatScheduledSkipEvent("e-1", makeEntry("Nightly") as never, DUE, [{ executionId: "run-1", kind: "execute", tasks: [{ taskId: "t-1", title: "Work", state: "running" }] }]);
  const sOut = lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content: skip, display: true }, {}, THEME)).join("\n");
  assert.ok(sOut.includes("SKIPPED (PREVIOUS RUN ACTIVE)"), "overlap skip status");
  assert.ok(sOut.includes("Inspect the active executions before re-dispatching"), "inspect instruction preserved");
});

test("scheduled-task-event collapsed: a dispatch-failure error containing uncertainty wording is not mislabeled", () => {
  const content = formatScheduledDispatchFailure("e-8", makeEntry("Flaky") as never, DUE, "the worker did not acknowledge within its bounded delivery window");
  const out = lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content, display: true }, {}, THEME)).join("\n");
  assert.ok(out.includes("DISPATCH FAILED"), "recognized from the head suffix, not the error text");
  assert.ok(!out.includes("UNKNOWN (MAY STILL ARRIVE)"), "uncertainty wording in the error does not flip the status");
  assert.ok(out.includes("the worker did not acknowledge within its bounded delivery window"), "the bounded error is preserved");
  assert.ok(out.includes("Fix the entry or its worker/review choices"), "repair instruction preserved");
});

test("scheduled-task-event collapsed: a multiline dispatch-failure error keeps every line", () => {
  const content = formatScheduledDispatchFailure("e-9", makeEntry("Multi") as never, DUE, "first error line\nsecond error line");
  const out = lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content, display: true }, {}, THEME)).join("\n");
  assert.ok(out.includes("first error line"), "first error line preserved");
  assert.ok(out.includes("second error line"), "second error line preserved (not dropped)");
  assert.ok(out.includes("Fix the entry or its worker/review choices"), "repair instruction preserved");
});

test("scheduled-task-event collapsed: one-shot pending skip and overdue drop recognized", () => {
  const oneShot = formatScheduledOneShotPendingSkip("e-2", makeEntry("Once") as never, DUE);
  assert.ok(lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content: oneShot, display: true }, {}, THEME)).join("\n").includes("SKIPPED (ONE-SHOT PENDING)"));
  const drop = formatScheduledOverdueDrop("e-3", makeEntry("Late") as never, DUE);
  assert.ok(lines(renderScheduledTaskEventCollapsed({ role: "custom", customType: "pi-review-scheduled-task-event", content: drop, display: true }, {}, THEME)).join("\n").includes("NOT RUN (OVERDUE DROP)"));
});

test("scheduled-task-event collapsed: multiline unknown event falls back to full content", () => {
  const body = "A historical scheduler note with no recognized outcome clause.\nSecond line of the retained text.";
  const message = { role: "custom", customType: "pi-review-scheduled-task-event", content: body, display: true };
  assert.equal(lines(renderScheduledTaskEventCollapsed(message, {}, THEME)).join("\n"), body);
});

// ── pi-review-scheduled-orchestrator-turn ────────────────────────────────────

test("scheduled-orchestrator-turn collapsed: recognized turn is a request, not an outcome; unknown falls back", () => {
  const message = {
    role: "custom", customType: "pi-review-scheduled-orchestrator-turn",
    content: 'Scheduled orchestrator turn for task e-7 (Daily digest) was due at 08:00 for cron "0 8 * * *".\nPerform the request below.\nThis is a scheduled request, not a completed outcome or an outcome report.',
    display: true, details: { entryId: "e-7", dueAt: "2026-01-01T08:00:00Z" },
  };
  const out = lines(renderScheduledOrchestratorTurnCollapsed(message, {}, THEME)).join("\n");
  assert.ok(out.includes("[scheduled-turn]"), "family label present");
  assert.ok(/not a completed outcome/i.test(out), "labeled a request, not an outcome");

  const unknown = { role: "custom", customType: "pi-review-scheduled-orchestrator-turn", content: "Some unrelated retained text.", display: true };
  assert.equal(lines(renderScheduledOrchestratorTurnCollapsed(unknown, {}, THEME)).join("\n"), "Some unrelated retained text.");
});

// ── Shared expanded view + fallback ──────────────────────────────────────────

test("renderFullMessageContent: complete text with control bytes made visible", () => {
  const message = { role: "custom", customType: "pi-review-bg-shell", content: "line one\n\x1b[31mred\x1b[0m line two", display: true };
  const out = lines(renderFullMessageContent(message, {}, THEME)).join("\n");
  assert.ok(out.includes("line one"), "full text retained");
  assert.ok(!out.includes("\x1b["), "raw control bytes are not emitted");
});

test("renderFullMessageContent: empty content shows a truthful placeholder", () => {
  const out = lines(renderFullMessageContent({ role: "custom", customType: "pi-review-bg-shell", content: "", display: true }, {}, THEME)).join("\n");
  assert.ok(out.includes("[no retained notification content]"));
});

test("registered subtask renderer ignores Task lines inside an inlined report", () => {
  const task = makeTask("t-current", "Actual research", "reported");
  const group = makeGroup("research", [task]);
  const report = formatResearchCompletion(
    "t-current", "Task: t-old · Earlier Git task · landed", "/tmp/report.md",
  );
  const content = formatExecutionEvent(group as never, task as never, "completion", report);
  const registered = new Map<string, (message: unknown, options: unknown, theme: unknown) => unknown>();
  registerNotificationMessageRenderers({
    registerMessageRenderer: (type: string, renderer: (message: unknown, options: unknown, theme: unknown) => unknown) => {
      registered.set(type, renderer);
    },
  });
  const renderer = registered.get("pi-review-subtask-event")!;
  for (const details of [undefined, { taskId: "t-current", executionId: "exec-1", state: "reported" }]) {
    const message = { role: "custom", customType: "pi-review-subtask-event", content, display: true, details };
    const out = lines(renderer(message, { expanded: false, outputPad: 1 }, THEME), 1000).join("\n");
    assert.ok(out.includes("[subtask] Actual research · REPORTED"));
    assert.ok(!out.includes("Earlier Git task"));
    assert.ok(!out.includes("LANDED"));
    assert.ok(out.includes("Full report: /tmp/report.md"));
  }
});

// ── Registration ─────────────────────────────────────────────────────────────

test("registration: registers exactly the five types and reports success", () => {
  const seen: string[] = [];
  const ok = registerNotificationMessageRenderers({ registerMessageRenderer: (type: string) => { seen.push(type); } });
  assert.equal(ok, true);
  assert.deepEqual(seen, [...NOTIFICATION_MESSAGE_TYPES]);
});

test("registration: returns false and registers nothing when the API is absent", () => {
  const ok = registerNotificationMessageRenderers({ notARegistration: () => {} });
  assert.equal(ok, false);
});
